### ISSUE TITLE
[Not really an issue] - Extraneous line

### ISSUE THREAD

**Issue by noejon** [schuettc/cdk-private-rds-with-lambda#107]
Hi Court,

Thanks for the article, I am at the moment following the tutorial and came across this line in your source code.

https://github.com/schuettc/cdk-private-rds-with-lambda/blob/f0e0b4a5d498ededcb72c27a7ad1267c5d6f5b30/src/rds.ts#L38C31-L38C46

I believe it is not doing anything as allowInternally is not actually called.

**Comment by schuettc** [comment]
Thanks!  Removed here: https://github.com/schuettc/cdk-private-rds-with-lambda/commit/d894614add4eaca913aa02b393e159054b942ce1
