### ISSUE TITLE
Custom resource is failing 

### ISSUE THREAD

**Issue by hosamshahin** [schuettc/cdk-private-rds-with-lambda#96]
I'm getting the following error from customResourceResult, any idea?

11:07:04 PM | CREATE_FAILED        | AWS::CloudFormation::CustomResource         | initialize/customResourceResult/Default
Received response status [FAILED] from custom resource. Message returned: Error: Unable to import module 'index': No module named 'psycopg2._psycopg'

**Comment by schuettc** [comment]
https://github.com/schuettc/cdk-private-rds-with-lambda/commit/f8df432df136982b167688c0caf229e3c2ecb304

This should fix that issue.  Updated with several other fixes as well.
